<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="9.0.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.0" />
    <PackageReference Include="QuestPDF" Version="2025.1.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Application\ReportingService.Application.csproj" />
    <ProjectReference Include="..\Domain\ReportingService.Domain.csproj" />
  </ItemGroup>

</Project>
