-- MassTransit EF Core transactional outbox / inbox (idempotent).
-- Required when EnsureCreated already ran on an older schema without these tables.
-- Applied automatically on service startup via WePlatform.Messaging.MassTransitOutboxInboxSchema.

CREATE TABLE IF NOT EXISTS public."InboxState" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "MessageId" uuid NOT NULL,
    "ConsumerId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Received" timestamp with time zone NOT NULL,
    "ReceiveCount" integer NOT NULL,
    "ExpirationTime" timestamp with time zone,
    "Consumed" timestamp with time zone,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_InboxState" PRIMARY KEY ("Id"),
    CONSTRAINT "AK_InboxState_MessageId_ConsumerId" UNIQUE ("MessageId", "ConsumerId")
);

CREATE TABLE IF NOT EXISTS public."OutboxState" (
    "OutboxId" uuid NOT NULL,
    "LockId" uuid NOT NULL,
    "RowVersion" bytea,
    "Created" timestamp with time zone NOT NULL,
    "Delivered" timestamp with time zone,
    "LastSequenceNumber" bigint,
    CONSTRAINT "PK_OutboxState" PRIMARY KEY ("OutboxId")
);

CREATE TABLE IF NOT EXISTS public."OutboxMessage" (
    "SequenceNumber" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "EnqueueTime" timestamp with time zone,
    "SentTime" timestamp with time zone NOT NULL,
    "Headers" text,
    "Properties" text,
    "InboxMessageId" uuid,
    "InboxConsumerId" uuid,
    "OutboxId" uuid,
    "MessageId" uuid NOT NULL,
    "ContentType" character varying(256) NOT NULL,
    "MessageType" text NOT NULL,
    "Body" text NOT NULL,
    "ConversationId" uuid,
    "CorrelationId" uuid,
    "InitiatorId" uuid,
    "RequestId" uuid,
    "SourceAddress" character varying(256),
    "DestinationAddress" character varying(256),
    "ResponseAddress" character varying(256),
    "FaultAddress" character varying(256),
    "ExpirationTime" timestamp with time zone,
    CONSTRAINT "PK_OutboxMessage" PRIMARY KEY ("SequenceNumber")
);

CREATE INDEX IF NOT EXISTS "IX_InboxState_Delivered"
    ON public."InboxState" USING btree ("Delivered");

CREATE INDEX IF NOT EXISTS "IX_OutboxState_Created"
    ON public."OutboxState" USING btree ("Created");

CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_EnqueueTime"
    ON public."OutboxMessage" USING btree ("EnqueueTime");

CREATE INDEX IF NOT EXISTS "IX_OutboxMessage_ExpirationTime"
    ON public."OutboxMessage" USING btree ("ExpirationTime");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_InboxMessageId_InboxConsumerId_SequenceNumber"
    ON public."OutboxMessage" USING btree ("InboxMessageId", "InboxConsumerId", "SequenceNumber");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_OutboxMessage_OutboxId_SequenceNumber"
    ON public."OutboxMessage" USING btree ("OutboxId", "SequenceNumber");

DO $$
BEGIN
    ALTER TABLE public."OutboxMessage"
        ADD CONSTRAINT "FK_OutboxMessage_InboxState_InboxMessageId_InboxConsumerId"
        FOREIGN KEY ("InboxMessageId", "InboxConsumerId")
        REFERENCES public."InboxState" ("MessageId", "ConsumerId");
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
    ALTER TABLE public."OutboxMessage"
        ADD CONSTRAINT "FK_OutboxMessage_OutboxState_OutboxId"
        FOREIGN KEY ("OutboxId")
        REFERENCES public."OutboxState" ("OutboxId");
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;
